// <auto-generated />
using System;
using ConsoleApp_Codefirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConsoleApp_Codefirst.Migrations
{
    [DbContext(typeof(SchoolDbCph))]
    partial class SchoolDbCphModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("AddressSequence");

            modelBuilder.HasSequence("CourseSequence");

            modelBuilder.HasSequence("GradeSequence");

            modelBuilder.HasSequence("LibraryCardSequence");

            modelBuilder.HasSequence("PersonSequence");

            modelBuilder.Entity("ConsoleApp_Codefirst.Address", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [AddressSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("ID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Addresses");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [CourseSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseID");

                    b.ToTable("Courses");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.Grade", b =>
                {
                    b.Property<int>("gradeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [GradeSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("gradeID"));

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("gradeID");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.LibraryCard", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [LibraryCardSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentedBooks")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("LibraryCards");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR [PersonSequence]");

                    SqlServerPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<int>("AddressID")
                        .HasColumnType("int");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LibraryCardUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressID");

                    b.HasIndex("LibraryCardUserId");

                    b.ToTable("People");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.Property<int>("coursesCourseID")
                        .HasColumnType("int");

                    b.HasKey("StudentsId", "coursesCourseID");

                    b.HasIndex("coursesCourseID");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("CourseTeacher", b =>
                {
                    b.Property<int>("TeachersId")
                        .HasColumnType("int");

                    b.Property<int>("coursesCourseID")
                        .HasColumnType("int");

                    b.HasKey("TeachersId", "coursesCourseID");

                    b.HasIndex("coursesCourseID");

                    b.ToTable("CourseTeacher");
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.Student", b =>
                {
                    b.HasBaseType("ConsoleApp_Codefirst.Person");

                    b.Property<int>("studentID")
                        .HasColumnType("int");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.Teacher", b =>
                {
                    b.HasBaseType("ConsoleApp_Codefirst.Person");

                    b.Property<int>("TeacherID")
                        .HasColumnType("int");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.Grade", b =>
                {
                    b.HasOne("ConsoleApp_Codefirst.Student", null)
                        .WithMany("grades")
                        .HasForeignKey("StudentId");
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.Person", b =>
                {
                    b.HasOne("ConsoleApp_Codefirst.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp_Codefirst.LibraryCard", "LibraryCard")
                        .WithMany()
                        .HasForeignKey("LibraryCardUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("LibraryCard");
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("ConsoleApp_Codefirst.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp_Codefirst.Course", null)
                        .WithMany()
                        .HasForeignKey("coursesCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTeacher", b =>
                {
                    b.HasOne("ConsoleApp_Codefirst.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeachersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConsoleApp_Codefirst.Course", null)
                        .WithMany()
                        .HasForeignKey("coursesCourseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConsoleApp_Codefirst.Student", b =>
                {
                    b.Navigation("grades");
                });
#pragma warning restore 612, 618
        }
    }
}
