// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WinFormsApp_DatabaseFirst.Models;

#nullable disable

namespace WinFormsApp_DatabaseFirst.Migrations
{
    [DbContext(typeof(SchoolDbringsted1Context))]
    partial class SchoolDbringsted1ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourseID");

                    b.HasKey("StudentId", "CourseId")
                        .HasName("PK__StudentC__5E57FD615B482283");

                    b.HasIndex("CourseId");

                    b.ToTable("StudentCourses", (string)null);
                });

            modelBuilder.Entity("StudentGrade", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GradeID");

                    b.HasKey("StudentId", "GradeId")
                        .HasName("PK__StudentG__578AADDA82164904");

                    b.HasIndex("GradeId");

                    b.ToTable("StudentGrades", (string)null);
                });

            modelBuilder.Entity("TeacherCourse", b =>
                {
                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourseID");

                    b.HasKey("TeacherId", "CourseId")
                        .HasName("PK__TeacherC__81608E5C724E541B");

                    b.HasIndex("CourseId");

                    b.ToTable("TeacherCourses", (string)null);
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Street")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Addresse__3214EC27E9791045");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Course", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CourseID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CourseId")
                        .HasName("PK__Courses__C92D718750F193D9");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Grade", b =>
                {
                    b.Property<Guid>("GradeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GradeID");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("GradeId")
                        .HasName("PK__Grades__54F87A379A37D90F");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.LibraryCard", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RentedBooks")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__LibraryC__1788CCACEB43875F");

                    b.ToTable("LibraryCards");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AddressID");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Persons__3214EC272BB401AD");

                    b.HasIndex("AddressId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Student", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PersonID");

                    b.Property<float?>("AverageMark")
                        .HasColumnType("real");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasKey("PersonId")
                        .HasName("PK__Students__AA2FFB857813EE85");

                    b.HasIndex(new[] { "StudentId" }, "UQ__Students__32C52A78BF53C87A")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Teacher", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PersonID");

                    b.Property<float?>("Salary")
                        .HasColumnType("real");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("TeacherID");

                    b.HasKey("PersonId")
                        .HasName("PK__Teachers__AA2FFB857D29BF98");

                    b.HasIndex(new[] { "TeacherId" }, "UQ__Teachers__EDF25945DBF975D4")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("StudentCourse", b =>
                {
                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentCo__Cours__4D5F7D71");

                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .HasPrincipalKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentCo__Stude__4C6B5938");
                });

            modelBuilder.Entity("StudentGrade", b =>
                {
                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Grade", null)
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentGr__Grade__51300E55");

                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .HasPrincipalKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__StudentGr__Stude__503BEA1C");
                });

            modelBuilder.Entity("TeacherCourse", b =>
                {
                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__TeacherCo__Cours__55009F39");

                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Teacher", null)
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .HasPrincipalKey("TeacherId")
                        .IsRequired()
                        .HasConstraintName("FK__TeacherCo__Teach__540C7B00");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.LibraryCard", b =>
                {
                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Person", "User")
                        .WithOne("LibraryCard")
                        .HasForeignKey("WinFormsApp_DatabaseFirst.Models.LibraryCard", "UserId")
                        .IsRequired()
                        .HasConstraintName("FK__LibraryCa__UserI__3E1D39E1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Person", b =>
                {
                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Address", "Address")
                        .WithMany("People")
                        .HasForeignKey("AddressId")
                        .HasConstraintName("FK__Persons__Address__3B40CD36");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Student", b =>
                {
                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Person", "Person")
                        .WithOne("Student")
                        .HasForeignKey("WinFormsApp_DatabaseFirst.Models.Student", "PersonId")
                        .IsRequired()
                        .HasConstraintName("FK__Students__Person__41EDCAC5");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Teacher", b =>
                {
                    b.HasOne("WinFormsApp_DatabaseFirst.Models.Person", "Person")
                        .WithOne("Teacher")
                        .HasForeignKey("WinFormsApp_DatabaseFirst.Models.Teacher", "PersonId")
                        .IsRequired()
                        .HasConstraintName("FK__Teachers__Person__45BE5BA9");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Address", b =>
                {
                    b.Navigation("People");
                });

            modelBuilder.Entity("WinFormsApp_DatabaseFirst.Models.Person", b =>
                {
                    b.Navigation("LibraryCard");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
